---
playbooks:
  - playbooks/**/!(**.md)
  - molecule/playbooks/**
common:
  - roles/common/**/!(**.md)
  - molecule/common/**
dns:
  - roles/dns/**/!(**.md)
  - molecule/dns/**
msmtp:
  - roles/msmtp/**/!(**.md)
  - molecule/msmtp/**
nfs:
  - roles/nfs/**/!(**.md)
  - molecule/nfs/**
nut:
  - roles/nut/**/!(**.md)
  - molecule/nut/**
qemu_guest_agent:
  - roles/qemu_guest_agent/**/!(**.md)
  - molecule/qemu_guest_agent/**
