---
default:
  - .github/workflows/test.yml
playbooks:
  - playbooks/**/!(**.md)
  - molecule/playbooks/**
access:
  - roles/access/**/!(**.md)
  - molecule/access/**
common:
  - roles/common/**/!(**.md)
  - molecule/common/**
dns:
  - roles/dns/**/!(**.md)
  - molecule/dns/**
logs:
  - roles/logs/**/!(**.md)
  - molecule/logs/**
misc:
  - roles/misc/**/!(**.md)
  - molecule/misc/**
mounts:
  - roles/mounts/**/!(**.md)
  - molecule/mounts/**
msmtp:
  - roles/msmtp/**/!(**.md)
  - molecule/msmtp/**
nfs:
  - roles/nfs/**/!(**.md)
  - molecule/nfs/**
nut:
  - roles/nut/**/!(**.md)
  - molecule/nut/**
packages:
  - roles/packages/**/!(**.md)
  - molecule/packages/**
proxmox:
  - roles/proxmox/**/!(**.md)
  - molecule/proxmox/**
qemu_guest_agent:
  - roles/qemu_guest_agent/**/!(**.md)
  - molecule/qemu_guest_agent/**
sanoid:
  - roles/sanoid/**/!(**.md)
  - molecule/sanoid/**
wireguard:
  - roles/wireguard/**/!(**.md)
  - molecule/wireguard/**
