---
name-template: 'Release v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

categories:
  - title: '🚨 Breaking changes'
    when:
      label: breaking
  - title: '✨ Enhancements'
    when:
      labels:
        - enhancement
        - security
        - refactor
  - title: '🐛 Bug fixes'
    when:
      label: bug
  - title: '📚 Documentation'
    when:
      label: documentation
  - title: '📦 Dependency Updates'
    when:
      label: dependencies
  - type: version-resolver
    semver-increment: major
    when:
      labels:
        - major
        - breaking
  - type: version-resolver
    semver-increment: minor
    when:
      labels:
        - minor
        - enhancement
        - security
  - type: version-resolver
    semver-increment: patch

template: |
  ## What’s changed

  $CHANGES
