---
namespace: vladgh
name: system
version: 1.9.1
readme: README.md
authors:
  - Vlad Ghinea <vlad@ghn.me> (https://ghn.me)
description: Ansible collection that holds roles, that can be used to configure common system services.
license_file: LICENSE
tags:
  - common
  - dns
  - hashicorp
  - linux
  - logs
  - msmtp
  - nfs
  - nut
  - proxmox
  - qemu
  - sanoid
  - shellcheck
  - system
  - ubuntu
  - wireguard
  - zsh
dependencies:
  ansible.posix: "*"
  community.general: "*"
repository: https://github.com/vladgh/ansible-collection-vladgh-system
documentation: https://github.com/vladgh/ansible-collection-vladgh-system
homepage: https://github.com/vladgh/ansible-collection-vladgh-system
issues: https://github.com/vladgh/ansible-collection-vladgh-system/issues
