---
collections:
  - name: ansible.posix
    version: 1.5.4
  - name: community.crypto
    version: 2.14.1
  - name: community.general
    version: 7.1.0
  - name: community.docker
    version: 3.4.8
