---
- name: Update Apt Cache
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true
  register: proxmox_pve_update_apt_cache
  until: proxmox_pve_update_apt_cache is success
  retries: 3
  delay: 2

- name: Regenerate initramfs
  ansible.builtin.command: update-initramfs -u
  changed_when: true
  when: not skip_initramfs | default(false)

- name: Update Grub
  ansible.builtin.command: update-grub
  changed_when: true
  when: not skip_grub | default(false)

- name: Reboot
  ansible.builtin.reboot:
    msg: Rebooting the hypervisor
  when: not skip_reboot | default(false)
