---
dependency:
  name: galaxy
  options:
    ignore-certs: True
    ignore-errors: True
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: instance
    image: ${MOLECULE_DISTRO:-'ubuntu:jammy'}
    dockerfile: ../Dockerfile.j2
    pre_build_image: false
    privileged: true
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  log: true
  playbooks:
    prepare: ../prepare-custom.yml
