---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: Include sanoid role
      ansible.builtin.include_role:
        name: vladgh.system.sanoid
      vars:
        sanoid_templates:
          default:
            frequently: 4
            hourly: 24
            daily: 7
            monthly: 12
            yearly: 1
            autosnap: true
            autoprune: true
        sanoid_datasets:
          tank/dataset:
            use_template: default
