{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

{% if item.env is defined %}
{% for var, value in item.env.items() %}
{% if value %}
ENV {{ var|upper }} {{ value }}
{% endif %}
{% endfor %}
{% endif %}

RUN apt-get -qy update && apt-get install -qy python sudo bash ca-certificates iproute2 zip init && \
    apt-get -qy autoremove && apt-get -qy clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/
