---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: Include common role
      ansible.builtin.include_role:
        name: vladgh.system.common
      vars:
        common_timezone: US/Central
        common_cron_jobs:
          - name: Testing
            minute: '0'
            job: ls -lah > /dev/null
        common_bash_extra_aliases:
          - alias: ll
            command: ls -lahpF
            dest: /root/.bashrc
            owner: root
            group: root
        common_sysctl_overwrite:
          fs.inotify.max_user_watches: 524288
        common_shell_extra_commands:
          - name: Test
            cmd: touch test.txt
            chdir: /tmp
            creates: test.txt
