---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    groups:
      - ansible
    image: ${MOLECULE_DISTRO:-'ubuntu:focal'}
    dockerfile: ../resources/Dockerfile.j2
    pre_build_image: false
    privileged: true
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      remote_tmp: /tmp/ansible-${USER}
  playbooks:
    prepare: ../resources/prepare.yml
lint: |
  set -e
  yamllint .
  ansible-lint .
