---
- name: Converge
  hosts: all
  become: yes

  pre_tasks:
    - name: Update apt cache.
      package:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'
    - name: Ensure auth.log file is present.
      copy:
        dest: /var/log/auth.log
        content: ""
        force: false
        mode: 0644
      when: ansible_distribution == 'Debian'

  tasks:
    - name: Include shellcheck role
      include_role:
        name: vladgh.system.shellcheck
