---
- name: Converge
  hosts: all
  become: true
  roles:
    - ./roles/proxmox
  pre_tasks:
    - name: Ensure required directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      loop:
        - /etc/lvm
        - /var/log/chrony
    - name: Ensure required directories
      ansible.builtin.file:
        path: /run/chrony
        state: directory
        mode: 0777
    - name: Ensure required files
      ansible.builtin.copy:
        content: ''
        dest: "{{ item }}"
        force: no
        group: root
        owner: root
        mode: 0664
      loop:
        - /etc/default/grub
        - /etc/lvm/lvm.conf
  vars:
    skip_reboot: yes
    skip_grub: yes
    skip_initramfs: yes
    proxmox_enable_chrony: yes
    proxmox_gpu_passthrough_enabled: yes
    proxmox_lvm_thin_pool_autoextend: yes
    proxmox_zfs_tune: yes
