---
- name: Converge
  hosts: all
  become: true
  pre_tasks:
    - name: Ensure required directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      loop:
        - /etc/lvm
    - name: Ensure required files
      ansible.builtin.copy:
        content: ''
        dest: "{{ item }}"
        force: false
        group: root
        owner: root
        mode: 0664
      loop:
        - /etc/default/grub
        - /etc/lvm/lvm.conf
  tasks:
    - name: Include proxmox role
      ansible.builtin.include_role:
        name: vladgh.system.proxmox
      vars:
        skip_reboot: true
        skip_grub: true
        skip_initramfs: true
        proxmox_gpu_passthrough_enabled: true
        proxmox_lvm_thin_pool_autoextend: true
        proxmox_zfs_tune: true
