---
- name: Update Apt Cache
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true
  register: _pve_update_apt_cache
  until: _pve_update_apt_cache is success
  retries: 3
  delay: 2

- name: Regenerate initramfs
  ansible.builtin.command: bash update-initramfs -u
  register: proxmox_initramfs_output
  changed_when: proxmox_initramfs_output.rc != 0
  when:
    - not skip_initramfs | default(false)

- name: Update Grub
  ansible.builtin.command: bash update-grub
  register: proxmox_grub_output
  changed_when: proxmox_grub_output.rc != 0
  when:
    - not skip_grub | default(false)

- name: Reboot
  ansible.builtin.reboot:
    msg: Rebooting the hypervisor
  when:
    - not skip_reboot | default(false)
