---
- name: Ensure Crontab is installed
  ansible.builtin.package:
    name: "{{ crontab_package_name }}"

- name: Cron jobs
  ansible.builtin.cron:
    name: "{{ item.name }}"
    user: "{{ item.user | default(omit) }}"
    minute: "{{ item.minute | default(omit) }}"
    hour: "{{ item.hour | default(omit) }}"
    day: "{{ item.day | default(omit) }}"
    month: "{{ item.month | default(omit) }}"
    weekday: "{{ item.weekday | default(omit) }}"
    special_time: "{{ item.special_time | default(omit) }}"
    job: "{{ item.job }}"
    state: "{{ item.state | default(omit) }}"
  loop: "{{ cron_jobs }}"
