---
- name: Timezone
  ansible.builtin.import_tasks: timezone.yml
  when: common_timezone is defined and common_timezone | length > 0

- name: Cron jobs
  ansible.builtin.import_tasks: cron.yml
  when: common_cron_jobs is defined and common_cron_jobs | length > 0

- name: SysCtl overrides
  ansible.builtin.import_tasks: sysctl.yml
  when: common_sysctl_overwrite is defined and common_sysctl_overwrite | length > 0

- name: Extra BASH aliases
  ansible.builtin.import_tasks: aliases.yml
  when: common_bash_extra_aliases is defined and common_bash_extra_aliases | length > 0

- name: Extra shell commands
  ansible.builtin.import_tasks: shell.yml
  when: common_shell_extra_commands is defined and common_shell_extra_commands | length > 0
