---
- name: Upgrade everything
  hosts: upgrade
  tasks:
    - name: Upgrade Debian Systems
      when: ansible_facts['os_family'] is defined and ansible_facts['os_family'] == 'Debian'
      block:
        - name: Update apt-get repo and cache
          ansible.builtin.apt:
            update_cache: true
            force_apt_get: true
            cache_valid_time: 21600  # Update the apt cache if its older than 6 hours
        - name: Upgrade all apt packages
          ansible.builtin.apt:
            upgrade: dist
        - name: Remove dependencies that are no longer required
          ansible.builtin.apt:
            autoremove: true
            purge: true
        - name: Remove useless packages from the cache
          ansible.builtin.apt:
            autoclean: true
