---
- name: Ensure ACL is installed for file permission controls
  ansible.builtin.package:
    name: acl
    state: present
  when: ansible_facts['distribution'] == 'Ubuntu' and ansible_facts['distribution_version'] is version('20.04', '<=')

- name: Check if logind.conf exists
  ansible.builtin.stat:
    path: /etc/systemd/logind.conf
  register: misc_systemd_logind_conf
  when: misc_disable_lid_switch is defined and misc_disable_lid_switch | bool

- name: Disable lid switch
  ansible.builtin.lineinfile:
    dest: /etc/systemd/logind.conf
    regexp: HandleLidSwitch
    line: 'HandleLidSwitch=lock'
  notify: Restart LoginD
  when: misc_disable_lid_switch is defined and misc_disable_lid_switch | bool and misc_systemd_logind_conf.stat.exists
